print("Hello I am happiness bot!")
name=input("What is your name?")
feeling=input("How are you feeling "+name+"?")
print("I sometimes feel "+feeling+".")
kidYear=input("What year were you born?")
print("So you are",2021-int (kidYear),"years old?")
print("Can you guess what year I was born?")
birth_year = input()
print("Woah, how did you know?")
print("In 300 years It will be",2021+300)
print("and I will be", 2021-int(birth_year)+300)
input("How old will you be in 20 years?")
print("Wow, nice math!")
print("Before I go let me tell you a computer joke.")
print("What will this computer have for lunch?")
print("a byte of a microchip, and some cookies from a website!")
print("Have a wonderful day, goodbye " +name+"!")
