print("But there's one sound that no one knows?")
data=input()
print("Ring-ding-ding-ding-dingeringeding")
print("Wa-pa-pa-pa-pa-pa-pow")
print("Hatee-hatee-hatee-ho!")
print("Jacha-chacha-chacha-chow!")
print("Fraka-kaka-kaka-kaka-kow!")
print("A-hee-ahee ha-hee!")
print ("A-oo-oo-oo-ooo!Woo-oo-oo-ooo!") 
